void initScreen();
void clearScreen();
void drawHeader(const char *);
void drawIPHeader(const char *);
void drawInitMenu(int);
void drawWifiMenu(int);
void drawMenu(int);
void drawError(int);
void drawSetupMenu(int);
void drawInitSelect();
void drawPressed(int);
void drawFooterCommands(const char *);
void setupMenu(int);
void handleMenu(int, int);